<html>
<head>
<title>Three things you didn’t know about exception handling in Dart and Flutter</title>
<link href="../Styles/Style.css" type="text/css" rel="stylesheet"/>
</head>
<body>
<h1 class="translated">关于Dart和Flutter中的异常处理，你不知道的三件事</h1>
<blockquote>原文：<a href="https://levelup.gitconnected.com/three-things-you-didnt-know-about-exception-handling-in-dart-and-flutter-d021e1458f08?source=collection_archive---------1-----------------------#2021-03-06">https://levelup.gitconnected.com/three-things-you-didnt-know-about-exception-handling-in-dart-and-flutter-d021e1458f08?source=collection_archive---------1-----------------------#2021-03-06</a></blockquote><div><div class="fc ih ii ij ik il"/><div class="im in io ip iq"><div class=""/><figure class="gl gn jr js jt ju gh gi paragraph-image"><div role="button" tabindex="0" class="jv jw di jx bf jy"><div class="gh gi jq"><img src="../Images/cdebe6f3caa48537f1fbc8b6025644b8.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/0*7Z_2GOPcI6w3Ex25"/></div></div><figcaption class="kb kc gj gh gi kd ke bd b be z dk translated">本·赫尔希在<a class="ae kf" href="https://unsplash.com?utm_source=medium&amp;utm_medium=referral" rel="noopener ugc nofollow" target="_blank"> Unsplash </a>上的照片</figcaption></figure><p id="e7fb" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">很抱歉这篇文章的标题是clickbait，我正在尝试不同的风格…但我不想让你失望，我会提供所有这三样东西:)</p><p id="7aad" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated"><strong class="ki iu">什么是例外？</strong></p><p id="80e8" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">有两种类型的异常定义:</p><ol class=""><li id="142e" class="le lf it ki b kj kk kn ko kr lg kv lh kz li ld lj lk ll lm bi translated"><strong class="ki iu">一个例外是一项操作无法履行其合同</strong></li><li id="4a9b" class="le lf it ki b kj ln kn lo kr lp kv lq kz lr ld lj lk ll lm bi translated"><strong class="ki iu">异常是一种意外的行为</strong></li></ol><p id="8a21" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">第一个定义似乎可以包括第二个定义，因为意外行为可能是运营无法履行合同的原因之一。其他原因可能包括或多或少的预期问题，如连接丢失、文件损坏等。</p><p id="e308" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">作为一个例子，让我们考虑这个函数:</p><figure class="ls lt lu lv gt ju"><div class="bz fp l di"><div class="lw lx l"/></div></figure><p id="9f04" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">这个函数返回我们账户中剩余的钱。为了做到这一点，该函数应该访问我们的后端并请求帐户余额，此操作可能会因为各种原因而失败-网络故障、服务器故障、前端和后端之间的合同被更改等。所有这些原因都会导致我们的操作无法履行其合同。然而，所有这些问题都是可以预见的，我们可以将它们添加到合同中。我们唯一不能期待的就是意料之外的行为:)。例如，我们预料到了所有的问题，除了一个:当后端在某些情况下返回文本“负数”而不是我们帐户的余额时——所以这对我们来说是意想不到的(这是一个完全人为的例子，但只是给你一个想法)。</p><p id="7d65" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">我们对我们的系统了解得越多，一些意外行为发生的可能性就越小。</p><p id="f64b" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">下一个问题是，在所有这些特殊情况下，我们将怎么办。我们是否希望对每种情况做出不同的反应，或者我们可能不太关心服务器是否停机或返回一些意外的数据？这是我们系统设计的问题，但无论如何，我们需要一种方法来单独捕捉这些异常或作为一般的异常情况，以便我们能够做出相应的响应。</p><p id="5d75" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated"><strong class="ki iu">不同语言的异常处理</strong></p><p id="d776" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">在不同的编程语言中，对上述考虑因素的考虑是不同的。让我们考虑Go、Rust和Dart用于处理异常的三种方法(我不是Go和Rust方面的专家，所以如果您发现代码有问题，请随意评论)。</p><p id="56c9" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">省道:</p><figure class="ls lt lu lv gt ju"><div class="bz fp l di"><div class="lw lx l"/></div></figure><p id="7c8a" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">去吧:</p><figure class="ls lt lu lv gt ju"><div class="bz fp l di"><div class="lw lx l"/></div></figure><p id="78c5" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">生锈:</p><figure class="ls lt lu lv gt ju"><div class="bz fp l di"><div class="lw lx l"/></div></figure><ol class=""><li id="5972" class="le lf it ki b kj kk kn ko kr lg kv lh kz li ld lj lk ll lm bi translated">在C++和Dart中使用的最常见的方法是主要关注快乐路径。所以代码非常容易阅读，并且没有被许多错误分支污染。另一方面，不太清楚哪个代码块会导致错误，以及会导致什么类型的错误。例如，在上面的例子中，如果你查看函数<em class="ly"> getRemainingAmount </em>内部，你很可能无法判断它是否会抛出异常。</li><li id="9828" class="le lf it ki b kj ln kn lo kr lp kv lq kz lr ld lj lk ll lm bi translated">在Go中，一切都围绕着错误处理展开。因此，除了值之外，函数还应该返回一个必须在函数调用后立即处理的错误。如果函数不能产生错误，它应该只返回一个结果，并且，它将清楚地表明函数是无错误的。没有办法默默地忽略一个错误，希望上游代码会处理它——当然，您可以忽略一个错误，但该错误不会自动传播到上游，您必须显式地这样做。</li><li id="11e6" class="le lf it ki b kj ln kn lo kr lp kv lq kz lr ld lj lk ll lm bi translated">在Rust中，有第三种处理异常/错误的方式。它看起来类似于Go:函数可以返回带有值或错误的类型，然后您可以使用模式匹配来了解它是值还是错误，以及返回了哪种错误。这不是强制性的，但没有其他方法抛出异常(除了<em class="ly"> panic </em>但这是另一个故事)，所以你可能想从所有可能导致错误的函数中返回任一类型。代码看起来非常可读，你不能不处理它就把异常/错误传递到上游(除非异常类型与上游函数中的完全相同)。</li></ol><p id="a513" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">这三种方法中的任何一种都可以用在Dart的代码中，你可以返回一个带有值和错误的对象，或者返回带有值或错误的结果，或者使用传统的<em class="ly"> try-catch </em>块和Dart提供的其他现成选项。</p><p id="c7ec" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">让我们探索一下Dart为我们提供了哪些异常处理选项。</p><p id="bc5c" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated"><strong class="ki iu">飞镖和颤振中的异常处理</strong></p><p id="ff66" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">我们需要使用异常处理的情况有哪些？</p><ol class=""><li id="025b" class="le lf it ki b kj kk kn ko kr lg kv lh kz li ld lj lk ll lm bi translated">同步码</li><li id="7ac7" class="le lf it ki b kj ln kn lo kr lp kv lq kz lr ld lj lk ll lm bi translated">异步代码</li><li id="815b" class="le lf it ki b kj ln kn lo kr lp kv lq kz lr ld lj lk ll lm bi translated">定时器</li><li id="e926" class="le lf it ki b kj ln kn lo kr lp kv lq kz lr ld lj lk ll lm bi translated">流</li><li id="2b23" class="le lf it ki b kj ln kn lo kr lp kv lq kz lr ld lj lk ll lm bi translated">颤振app整体</li></ol><p id="8a38" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated"><strong class="ki iu">同步码</strong></p><p id="dc0b" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">Dart中处理异常的主要工具是<em class="ly"> try-catch-finally </em>构造——和许多其他语言一样。</p><p id="2759" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">为了捕捉代码块中的所有异常，您将代码包装在<em class="ly"> try </em>块中，并使用多个<em class="ly"> on-catch </em>指令来处理一些特定的异常，然后使用<em class="ly"> catch </em>来处理所有其他意外异常，最后使用<em class="ly"> finally </em>来运行应该在<em class="ly"> try </em>块和任何<em class="ly"> catch </em>块中的代码之后调用的代码。即使你从<em class="ly"> try </em>或<em class="ly"> catch </em>块返回或者在<em class="ly"> catch </em>块中重新抛出异常，最后<em class="ly">中的代码也会被调用。</em></p><p id="8616" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">指令<em class="ly">重新抛出</em>帮助你在处理之后抛出同样的异常，这样上游代码会处理它。</p><figure class="ls lt lu lv gt ju"><div class="bz fp l di"><div class="lw lx l"/></div></figure><p id="fceb" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">输出:</p><pre class="ls lt lu lv gt lz ma mb mc aw md bi"><span id="5585" class="me mf it ma b gy mg mh l mi mj">Cant divide to zero<br/>Clean-up done 1</span><span id="9442" class="me mf it ma b gy mk mh l mi mj">Format exceptions FormatException: format is wrong<br/>Clean-up done 2</span><span id="182c" class="me mf it ma b gy mk mh l mi mj">Allocate something 3<br/>Unknown exceptions: Other error occurred, with stack: <br/>#0      main (file:///Users/user/Downloads/dart_sample/bin/sync_exceptions.dart:26:5)<br/>#1      _startIsolate.&lt;anonymous closure&gt; (dart:isolate-patch/isolate_patch.dart:299:32)<br/>#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)</span><span id="18ce" class="me mf it ma b gy mk mh l mi mj">Clean-up something 3<br/>Unhandled exception:<br/>Other error occurred<br/>#0      main (file:///Users/user/Downloads/dart_sample/bin/sync_exceptions.dart:26:5)<br/>#1      _startIsolate.&lt;anonymous closure&gt; (dart:isolate-patch/isolate_patch.dart:299:32)<br/>#2      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)</span></pre><p id="9f79" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">我们可以看到，所有三个<em class="ly"> try-catch </em>块都捕获了异常，在第三个块中，异常在清理完成后被重新抛出。</p><p id="73bf" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">对于处理同步代码块中的异常来说，这已经足够了。你可以在这里查看更多细节——https://dart.dev/guides/language/language-tour#catch</p><p id="6243" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated"><strong class="ki iu">异步代码</strong></p><p id="d029" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">让我们考虑这个例子:</p><figure class="ls lt lu lv gt ju"><div class="bz fp l di"><div class="lw lx l"/></div></figure><p id="dc38" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">输出:</p><pre class="ls lt lu lv gt lz ma mb mc aw md bi"><span id="b28d" class="me mf it ma b gy mg mh l mi mj">Everything is fine!<br/>Clean-up done<br/>Unhandled exception:<br/>IntegerDivisionByZeroException<br/>#0      int.~/ (dart:core-patch/integers.dart:22:7)<br/>#1      main.&lt;anonymous closure&gt; (file:///Users/user/Downloads/dart_sample/bin/async_exceptions.dart:6:21)<br/>#2      new Future.delayed.&lt;anonymous closure&gt; (dart:async/future.dart:325:39)<br/>#3      Timer._createTimer.&lt;anonymous closure&gt; (dart:async-patch/timer_patch.dart:18:15)<br/>#4      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)<br/>#5      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)<br/>#6      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)</span></pre><p id="78dc" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">我们希望在将来处理延迟一秒钟的异常。该代码未能捕获异常是很自然的，因为<em class="ly"> try-catch </em>块中的代码只是安排在<em class="ly"> try-catch </em>完成工作后一秒调用<em class="ly">计算</em>(期货回调/平仓)。</p><p id="8b7b" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">在时间轴上看起来大概是这样的:</p><figure class="ls lt lu lv gt ju gh gi paragraph-image"><div role="button" tabindex="0" class="jv jw di jx bf jy"><div class="gh gi ml"><img src="../Images/8b98f1d329edcc57c3c462d32389798d.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*RMHCVtR3_rW7poED_e-8Ig.png"/></div></div><figcaption class="kb kc gj gh gi kd ke bd b be z dk translated">捕获异步代码中的异常</figcaption></figure><p id="d33a" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">怎么修？有许多方法可以解决这个问题，例如，在<em class="ly">未来</em>之前添加<em class="ly">等待</em>指令。它强制在<em class="ly"> try-catch </em>内部调用<em class="ly">计算</em>，这样<em class="ly"> try </em>块将能够成功捕获并处理异常。</p><figure class="ls lt lu lv gt ju"><div class="bz fp l di"><div class="lw lx l"/></div></figure><p id="c759" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">输出:</p><pre class="ls lt lu lv gt lz ma mb mc aw md bi"><span id="6ff8" class="me mf it ma b gy mg mh l mi mj">Cant divide to zero<br/>Clean-up done</span></pre><p id="2cb7" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">现在它工作正常了，我们设法捕捉到了异常，并在之后进行了清理。</p><p id="7d85" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">我们可以这样表示新代码:</p><figure class="ls lt lu lv gt ju gh gi paragraph-image"><div role="button" tabindex="0" class="jv jw di jx bf jy"><div class="gh gi mm"><img src="../Images/a96ff60028730e67ba67d1511c47f5cb.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*jmxEdA271gvyEmGKGwJD1A.png"/></div></div></figure><p id="ccb6" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">如果我们有一个期货链呢？完全没问题，<em class="ly"> try-catch </em>会捕捉所有的异常，只要我们在第一个之前插入<em class="ly">wait</em>。</p><figure class="ls lt lu lv gt ju"><div class="bz fp l di"><div class="lw lx l"/></div></figure><p id="ccf7" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">输出:</p><pre class="ls lt lu lv gt lz ma mb mc aw md bi"><span id="04e7" class="me mf it ma b gy mg mh l mi mj">Its ok so far<br/>Cant divide to zero<br/>Clean-up done</span></pre><p id="15f0" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">如果你不喜欢上面捕捉异常的方式，你可以使用点语法和<em class="ly"> catchError </em>函数。</p><figure class="ls lt lu lv gt ju"><div class="bz fp l di"><div class="lw lx l"/></div></figure><p id="1151" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">输出:</p><pre class="ls lt lu lv gt lz ma mb mc aw md bi"><span id="f5f5" class="me mf it ma b gy mg mh l mi mj">Its ok so far<br/>Cant divide to zero<br/>Clean-up done</span></pre><p id="4527" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">在上面的代码中，<em class="ly"> catchError </em>是<em class="ly"> catch </em>块的模拟，<em class="ly"> whenComplete </em>是<em class="ly"> finally </em>块的模拟。函数<em class="ly"> catchError </em>捕捉位于它上面的所有代码中的异常，因此如果您怀疑<em class="ly">在Complete </em>时会抛出异常，您可以在它之后再添加一个<em class="ly"> catchError </em>。</p><figure class="ls lt lu lv gt ju"><div class="bz fp l di"><div class="lw lx l"/></div></figure><p id="3f3a" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">输出:</p><pre class="ls lt lu lv gt lz ma mb mc aw md bi"><span id="5a2f" class="me mf it ma b gy mg mh l mi mj">Its ok so far<br/>Cant divide to zero<br/>Clean-up done<br/>Oh, error in the finally block</span></pre><p id="95a8" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">您可以使用<em class="ly"> catchError </em>函数的<em class="ly"> test </em>参数进行异常匹配。</p><figure class="ls lt lu lv gt ju"><div class="bz fp l di"><div class="lw lx l"/></div></figure><p id="ff41" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">输出:</p><pre class="ls lt lu lv gt lz ma mb mc aw md bi"><span id="7872" class="me mf it ma b gy mg mh l mi mj">Its fie so far<br/>Then started<br/>All other exceptions: random exception<br/>Clean-up done</span></pre><p id="6929" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">看起来不是超级可读吧？这就是为什么Dart代码风格建议在这种情况下使用<em class="ly"> await ( </em> <a class="ae kf" href="https://dart.dev/guides/language/effective-dart/usage#prefer-asyncawait-over-using-raw-futures" rel="noopener ugc nofollow" target="_blank">代码风格指南</a>)和<em class="ly"> try-catch </em>。它可能看起来像这样:</p><figure class="ls lt lu lv gt ju"><div class="bz fp l di"><div class="lw lx l"/></div></figure><p id="f678" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">输出:</p><pre class="ls lt lu lv gt lz ma mb mc aw md bi"><span id="9b0f" class="me mf it ma b gy mg mh l mi mj">Its fie so far<br/>Then started<br/>All other exceptions: random exception<br/>Clean-up done</span></pre><p id="19fa" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">从我个人的角度来说，要清晰的多，可读性强。</p><p id="6e2a" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">此外，它还有一个优势——它可以处理同步和异步代码，因此如果您需要在两个异步调用之间进行一些计算，您不必创建额外的同步<em class="ly"> Future </em>(就像您在使用<em class="ly">点</em>语法的情况下所做的那样)，只需将这些代码添加到<em class="ly"> try </em>块中。</p><p id="392a" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">哦，这很简单，对吧？这段代码呢？</p><figure class="ls lt lu lv gt ju"><div class="bz fp l di"><div class="lw lx l"/></div></figure><pre class="ls lt lu lv gt lz ma mb mc aw md bi"><span id="599c" class="me mf it ma b gy mg mh l mi mj">Everything is fine!<br/>Clean-up done<br/>Timer runs.<br/>Unhandled exception:<br/>Exception: [Timer] Bad thing happens!<br/>#0      main.&lt;anonymous closure&gt; (file:///Users/user/Downloads/dart_sample/bin/async_exceptions.dart:7:7)<br/>#1      Timer._createTimer.&lt;anonymous closure&gt; (dart:async-patch/timer_patch.dart:18:15)<br/>#2      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)<br/>#3      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)<br/>#4      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)</span></pre><p id="eea8" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">:((笑中带哭)。是啊，计时器里也会发生不好的事情。上面的代码不能很好地处理这些不好的事情，因为定时器的<em class="ly">回调</em>将被调用，而不是在<em class="ly"> try-catch </em>块中，我们不能用<em class="ly"> await </em>指令来修复它，因为我们不能等待定时器。</p><p id="da47" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">一个显而易见的解决方案是在定时器回调中添加<em class="ly"> try-catch </em>，但是如果我们不想用异常处理来污染回调，或者在定时器回调中有一个非常复杂的异步逻辑，并且我们想在运行定时器的地方处理来自那个逻辑的异常？</p><p id="0dfc" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated"><strong class="ki iu">区域和运行区域防护</strong></p><p id="0d4d" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated"><em class="ly"> runZonedGuarded </em>可以帮你解决这个问题以及更复杂的情况！</p><p id="2aee" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated"><em class="ly"> Zones ( </em></p><p id="5868" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">它是如何工作的？计时器中的每个<em class="ly">回调</em>或<em class="ly">计算</em>、<em class="ly">微任务、</em>和<em class="ly">期货</em>被包装到Z <em class="ly"> one </em>中的一个特殊<em class="ly">处理程序</em>中。<em class="ly">处理程序</em>将<em class="ly">回调</em>包装在try-catch中，如果<em class="ly"> catch </em>被触发，则<em class="ly">区域</em>会调用一个未捕获的错误处理程序，您可以在其中处理这些错误。</p><p id="25ba" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">每段代码都在某个<em class="ly">区域</em>中运行，即使你没有创建你的自定义<em class="ly">区域</em>它也会在<em class="ly">根区域</em>中被调用，这意味着我们无论如何都是安全的！</p><p id="750a" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">让我们看看如何解决计时器的问题:</p><figure class="ls lt lu lv gt ju"><div class="bz fp l di"><div class="lw lx l"/></div></figure><p id="3f44" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">输出:</p><pre class="ls lt lu lv gt lz ma mb mc aw md bi"><span id="19f2" class="me mf it ma b gy mg mh l mi mj">Everything is fine!<br/>Timer runs.<br/>Exception handled Exception: [Timer] Bad thing happens!, <br/>#0      main.&lt;anonymous closure&gt;.&lt;anonymous closure&gt; (file:///Users/user/Downloads/dart_sample/bin/async_exceptions.dart:7:7)<br/>#1      _rootRun (dart:async/zone.dart:1182:47)<br/>#2      _CustomZone.run (dart:async/zone.dart:1093:19)<br/>#3      _CustomZone.runGuarded (dart:async/zone.dart:997:7)<br/>#4      _CustomZone.bindCallbackGuarded.&lt;anonymous closure&gt; (dart:async/zone.dart:1037:23)<br/>#5      _rootRun (dart:async/zone.dart:1190:13)<br/>#6      _CustomZone.run (dart:async/zone.dart:1093:19)<br/>#7      _CustomZone.bindCallback.&lt;anonymous closure&gt; (dart:async/zone.dart:1021:23)<br/>#8      Timer._createTimer.&lt;anonymous closure&gt; (dart:async-patch/timer_patch.dart:18:15)<br/>#9      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)<br/>#10     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)<br/>#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)</span></pre><p id="cbcd" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">轻松点。只需将您的代码包装到<strong class="ki iu"> runZonedGuarded </strong>中，并添加一个错误处理程序。没有异常可以挤过这个构造…直到我们不会在错误处理程序本身中抛出异常，因为错误处理程序是在父区域中调用的，所以要小心。</p><p id="8e8f" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">您可以注意到堆栈跟踪变得更长了，因为现在<em class="ly">异步</em> <em class="ly">回调</em>被包装到我们的<em class="ly"> _CustomZone </em>处理程序中。</p><p id="7a43" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">Zones 是一个非常强大的工具，可以帮助你将复杂异步逻辑的某些部分与应用程序的其他部分隔离开来。正如我们将在后面看到的，当你使用流和处理Flutter应用程序中未处理的异常时，它也非常有用。</p><p id="688c" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">如果我们试图描述区域中的异常处理，它可能是这样的:</p><figure class="ls lt lu lv gt ju gh gi paragraph-image"><div role="button" tabindex="0" class="jv jw di jx bf jy"><div class="gh gi mn"><img src="../Images/099029db98a41c7c09a84d59ac5dd9bd.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*y7Ac36Bay9tc2-RVoLAZ6A.png"/></div></div></figure><p id="97f3" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">在about图像中，我们可以看到，如果我们将这些回调安排在<em class="ly">区域</em>内，那么所有的异步回调都被<em class="ly">区域</em>的异常处理所覆盖。</p><p id="6c0c" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">此外，<em class="ly"> Zones </em>帮助您拦截计时器和打印操作符的创建，并在区域的上下文中保存一些参数(这是一个字典，您可以在创建它时传递给区域)。据我所知，所有那些先进的东西主要用于测试。</p><p id="7f59" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">这是一个我们如何使用<em class="ly">嵌套区域</em>和<em class="ly">区域的</em>上下文参数的例子——我添加了参数<em class="ly">区域名称</em>,在这里我写下<em class="ly">区域</em>的名称，并在输出中显示出来。</p><figure class="ls lt lu lv gt ju"><div class="bz fp l di"><div class="lw lx l"/></div></figure><p id="d62f" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">输出:</p><pre class="ls lt lu lv gt lz ma mb mc aw md bi"><span id="7836" class="me mf it ma b gy mg mh l mi mj">Current zone start in: Instance of '_RootZone'<br/>Current zone inside runZoned: Instance of '_CustomZone' with name First zone<br/>Current zone (1) inside runZoned: Instance of '_CustomZone' with name Second zone<br/>Everything is fine!<br/>Timer runs.<br/>Current zone inside catch: Instance of '_RootZone' with name null<br/>Exception handled Exception: [Timer] Bad thing happens!, <br/>#0      main.&lt;anonymous closure&gt;.&lt;anonymous closure&gt; (file:///Users/user/Downloads/dart_sample/bin/async_exceptions.dart:10:7)<br/>#1      _rootRun (dart:async/zone.dart:1182:47)<br/>#2      _CustomZone.run (dart:async/zone.dart:1093:19)<br/>#3      _CustomZone.runGuarded (dart:async/zone.dart:997:7)<br/>#4      _CustomZone.bindCallbackGuarded.&lt;anonymous closure&gt; (dart:async/zone.dart:1037:23)<br/>#5      _rootRun (dart:async/zone.dart:1190:13)<br/>#6      _CustomZone.run (dart:async/zone.dart:1093:19)<br/>#7      _CustomZone.bindCallback.&lt;anonymous closure&gt; (dart:async/zone.dart:1021:23)<br/>#8      Timer._createTimer.&lt;anonymous closure&gt; (dart:async-patch/timer_patch.dart:18:15)<br/>#9      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)<br/>#10     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)<br/>#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)</span><span id="09f1" class="me mf it ma b gy mk mh l mi mj">Timer 1 runs. <br/>Current zone (1) inside catch: Instance of '_CustomZone' with name First zone<br/>Exception handled (1) Exception: [Timer 1] Bad thing happens!, <br/>#0      main.&lt;anonymous closure&gt;.&lt;anonymous closure&gt;.&lt;anonymous closure&gt; (file:///Users/user/Downloads/dart_sample/bin/async_exceptions.dart:18:11)<br/>#1      _rootRun (dart:async/zone.dart:1182:47)<br/>#2      _CustomZone.run (dart:async/zone.dart:1093:19)<br/>#3      _CustomZone.runGuarded (dart:async/zone.dart:997:7)<br/>#4      _CustomZone.bindCallbackGuarded.&lt;anonymous closure&gt; (dart:async/zone.dart:1037:23)<br/>#5      _rootRun (dart:async/zone.dart:1190:13)<br/>#6      _CustomZone.run (dart:async/zone.dart:1093:19)<br/>#7      _CustomZone.bindCallback.&lt;anonymous closure&gt; (dart:async/zone.dart:1021:23)<br/>#8      Timer._createTimer.&lt;anonymous closure&gt; (dart:async-patch/timer_patch.dart:18:15)<br/>#9      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)<br/>#10     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)<br/>#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)</span></pre><p id="697e" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">从上面的例子中，您可以看到使用<em class="ly">嵌套区域</em>将您的代码划分为<em class="ly">无错误区域</em>是非常方便的，并且可能使用<em class="ly">区域的</em> <em class="ly">上下文</em>来保存如此有用的信息以用于日志记录目的。</p><p id="405d" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated"><strong class="ki iu">流中的错误处理</strong></p><p id="a806" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">我承诺揭示当我们使用流时，区域如何帮助处理异常。</p><p id="b543" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">让我们考虑一个简单的代码，其中一段代码向流发出一些事件，另一段代码使用它们。</p><figure class="ls lt lu lv gt ju"><div class="bz fp l di"><div class="lw lx l"/></div></figure><p id="7465" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">输出:</p><pre class="ls lt lu lv gt lz ma mb mc aw md bi"><span id="08e2" class="me mf it ma b gy mg mh l mi mj">43<br/>Unhandled exception:<br/>[Listener] Bad thing happens!<br/>#0      startListener.&lt;anonymous closure&gt; (file:///Users/artemgoncharov/Downloads/dart_sample/bin/streams_exceptions.dart:23:7)<br/>#1      _RootZone.runUnaryGuarded (dart:async/zone.dart:1384:10)<br/>#2      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)<br/>#3      _DelayedData.perform (dart:async/stream_impl.dart:611:14)<br/>#4      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)<br/>#5      _PendingEvents.schedule.&lt;anonymous closure&gt; (dart:async/stream_impl.dart:687:7)<br/>#6      _microtaskLoop (dart:async/schedule_microtask.dart:41:21)<br/>#7      _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)<br/>#8      _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)<br/>#9      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:404:11)<br/>#10     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)<br/>#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)<br/>44</span></pre><p id="36a3" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">我知道这段代码一点也不完美:)但是它演示了这个问题——我们在监听器中会有一个未处理的异常。一个显而易见的解决方案是在侦听器中添加<em class="ly"> try-catch </em>。同样，这可能很难，因为可能有多个侦听器和一些异步逻辑，我们可能希望在一个地方处理来自侦听器和业务逻辑的所有异常。</p><p id="51e8" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">我们将侦听器创建封装到一个<em class="ly">区域</em>中，将生产者创建封装到另一个区域中，现在我们可以从两端处理所有异常，并在一个非常方便的地方记录和/或恢复它们:</p><figure class="ls lt lu lv gt ju"><div class="bz fp l di"><div class="lw lx l"/></div></figure><p id="3b83" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">输出:</p><pre class="ls lt lu lv gt lz ma mb mc aw md bi"><span id="e5f6" class="me mf it ma b gy mg mh l mi mj">43<br/>44<br/>CONSUMER ZONE Exception handled: [Listener] Bad thing happens!, #0      startListener.&lt;anonymous closure&gt; (file:///Users/user/Downloads/dart_sample/bin/streams_exceptions.dart:35:7)<br/>#1      _rootRunUnary (dart:async/zone.dart:1206:13)<br/>#2      _CustomZone.runUnary (dart:async/zone.dart:1100:19)<br/>#3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)<br/>#4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:357:11)<br/>#5      _DelayedData.perform (dart:async/stream_impl.dart:611:14)<br/>#6      _StreamImplEvents.handleNext (dart:async/stream_impl.dart:730:11)<br/>#7      _PendingEvents.schedule.&lt;anonymous closure&gt; (dart:async/stream_impl.dart:687:7)<br/>#8      _rootRun (dart:async/zone.dart:1182:47)<br/>#9      _CustomZone.run (dart:async/zone.dart:1093:19)<br/>#10     _CustomZone.runGuarded (dart:async/zone.dart:997:7)<br/>#11     _CustomZone.bindCallbackGuarded.&lt;anonymous closure&gt; (dart:async/zone.dart:1037:23)<br/>#12     _rootRun (dart:async/zone.dart:1190:13)<br/>#13     _CustomZone.run (dart:async/zone.dart:1093:19)<br/>#14     _CustomZone.runGuarded (dart:async/zone.dart:997:7)<br/>#15     _CustomZone.bindCallbackGuarded.&lt;anonymous closure&gt; (dart:async/zone.dart:1037:23)<br/>#16     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)<br/>#17     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)<br/>#18     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)<br/>#19     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:404:11)<br/>#20     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)<br/>#21     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)</span><span id="4785" class="me mf it ma b gy mk mh l mi mj">45<br/>PRODUCER ZONE Exception handled: [Stream] Bad thing happens!, #0      getStream.&lt;anonymous closure&gt; (file:///Users/user/Downloads/dart_sample/bin/streams_exceptions.dart:24:18)<br/>#1      _rootRunUnary (dart:async/zone.dart:1198:47)<br/>#2      _CustomZone.runUnary (dart:async/zone.dart:1100:19)<br/>#3      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)<br/>#4      _CustomZone.bindUnaryCallbackGuarded.&lt;anonymous closure&gt; (dart:async/zone.dart:1042:26)<br/>#5      _rootRunUnary (dart:async/zone.dart:1206:13)<br/>#6      _CustomZone.runUnary (dart:async/zone.dart:1100:19)<br/>#7      _CustomZone.bindUnaryCallback.&lt;anonymous closure&gt; (dart:async/zone.dart:1026:26)<br/>#8      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:397:19)<br/>#9      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:428:5)<br/>#10     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)</span><span id="e0a3" class="me mf it ma b gy mk mh l mi mj">47<br/>48<br/>49<br/>50</span></pre><p id="cdee" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated"><strong class="ki iu">警告！</strong>我并不是说我们必须在错误可能出现的地方放弃处理错误，我只是说有时将复杂的特性包装到区域中非常有用，以便捕捉并正确记录有时会挤过我们所有下游堡垒的错误。</p><p id="826e" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">乐观地说，我将进入最后一个话题:<em class="ly">未处理的异常</em>。</p><p id="eba4" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated"><strong class="ki iu">未处理的异常</strong></p><p id="8228" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">正如我们之前看到的，所有的<em class="ly">未处理异常</em>都被调用代码的<em class="ly">区域</em>拦截。因此，如果您想记录您的<em class="ly"> flutter </em>应用程序中未处理的异常，您只需将您的<em class="ly"> runApp </em>调用包装到<em class="ly"> runZoneGuarded </em>中，并在错误处理程序中添加日志记录。如果您在<em class="ly"> main </em>函数中做了其他事情——创建提供者或单件——您可能也想将它们包装到<em class="ly"> runZonedGuarded </em>中。</p><p id="c2e3" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">这有助于您了解应用程序中任何未处理的异常。</p><p id="424d" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">你可能会争辩说，当你调试你的应用程序时，你可以在终端中看到它们。这对于调试来说非常方便，但是有两个细微差别:</p><ol class=""><li id="d501" class="le lf it ki b kj kk kn ko kr lg kv lh kz li ld lj lk ll lm bi translated">如果你直接在设备上调试你的应用程序(不是在<em class="ly">模拟器</em>上)，你将不会在<em class="ly">异步</em>代码中看到异常(除非你使用<em class="ly"> runZonedGuarded </em></li><li id="3507" class="le lf it ki b kj ln kn lo kr lp kv lq kz lr ld lj lk ll lm bi translated">在发布版本中，我敢肯定，你想知道所有的<em class="ly">未处理的异常</em>，即使看起来应用运行良好。因此，您需要添加<em class="ly"> runZonedGuarded </em>并将所有异常记录到您的后端或<em class="ly"> Firebase/Sentry </em>或您用于远程日志记录的任何系统</li></ol><p id="5852" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">然而，<em class="ly"> runZoneGuarded </em>不能帮助你处理已经被Flutter框架处理的异常。</p><p id="fe52" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">所有这些异常都可以使用<em class="ly"> FlutterError.onError </em>回调来记录。如果你在这个回调函数中添加了日志，那么任何时候Flutter捕捉到一个渲染错误或者小部件中的任何错误，它都会到达这个回调函数并被你记录下来。在添加onError回调之前，不要忘记使用<em class="ly">【widgetsflutterbinding . ensure initialized()</em><strong class="ki iu"/>。</p><figure class="ls lt lu lv gt ju"><div class="bz fp l di"><div class="lw lx l"/></div></figure><p id="5080" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated"><strong class="ki iu">总结</strong></p><p id="cf5a" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">简洁似乎不是我的特色之一，但我希望这篇文章仍然有用，能够对你有所帮助。</p><p id="9a35" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">此外，如果你还没有忘记书名中的三个东西，它们是:</p><ol class=""><li id="4172" class="le lf it ki b kj kk kn ko kr lg kv lh kz li ld lj lk ll lm bi translated">在不同的语言中有许多处理异常的方法，<em class="ly"> try-catch </em>不是唯一的一种，而且，这取决于你的设计你想要使用什么样的异常处理方法——在Dart中你可以实现其中的许多方法</li><li id="dd90" class="le lf it ki b kj ln kn lo kr lp kv lq kz lr ld lj lk ll lm bi translated">使用<em class="ly"> runZoneGuarded </em>来捕捉复杂的<em class="ly">异步代码</em>、<em class="ly">流、</em>以及整个<em class="ly"> Flutter </em> app中的异常</li><li id="3cca" class="le lf it ki b kj ln kn lo kr lp kv lq kz lr ld lj lk ll lm bi translated"><em class="ly">如果你在真实的设备上调试你的app，异步代码中未处理的异常</em>可能会被默默吞下(不在终端中打印)</li></ol></div><div class="ab cl mo mp hx mq" role="separator"><span class="mr bw bk ms mt mu"/><span class="mr bw bk ms mt mu"/><span class="mr bw bk ms mt"/></div><div class="im in io ip iq"><p id="6d70" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">这篇文章是在我在新加坡Flutter Meetup的演讲之后写的，你可以在这里找到:</p><div class="mv mw gp gr mx my"><a href="https://www.meetup.com/Singapore-Flutter-Meetup/events/276139032/" rel="noopener  ugc nofollow" target="_blank"><div class="mz ab fo"><div class="na ab nb cl cj nc"><h2 class="bd iu gy z fp nd fr fs ne fu fw is bi translated">颤振聚会#6</h2><div class="nf l"><h3 class="bd b gy z fp nd fr fs ne fu fw dk translated">在线加入下一次颤振聚会！议程:*下午1:00:Colin的“@协议-构建下一代注重隐私的应用程序”…</h3></div><div class="ng l"><p class="bd b dl z fp nd fr fs ne fu fw dk translated">www.meetup.com</p></div></div><div class="nh l"><div class="ni l nj nk nl nh nm jz my"/></div></div></a></div><p id="5d8d" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">meetup的主持人是一个很厉害的家伙:<a class="nn no ep" href="https://medium.com/u/ad77da678494?source=post_page-----d021e1458f08--------------------------------" rel="noopener" target="_blank">德国Saprykin </a>，他在扑闪方面超级懂行，好心帮我评论这篇文章。</p><p id="751c" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">谢谢你，德国人，邀请我参加会议并评论这篇文章！</p><p id="1490" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated">其他令人惊讶的与会者还有布雷特·摩根和科林·康斯特布尔T20。谢谢，伙计们非常有趣的介绍！</p><p id="2b1c" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated"><strong class="ki iu">来源列表</strong></p><p id="4c0d" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated"><a class="ae kf" href="https://api.flutter.dev" rel="noopener ugc nofollow" target="_blank">https://API . flutter . dev</a></p><p id="7536" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated"><a class="ae kf" href="https://dart.dev/get-dart" rel="noopener ugc nofollow" target="_blank">https://dart.dev/get-dart</a></p><p id="f09d" class="pw-post-body-paragraph kg kh it ki b kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la lb lc ld im bi translated"><a class="ae kf" href="https://github.com/flutter/flutter" rel="noopener ugc nofollow" target="_blank">https://github.com/flutter/flutter</a></p><div class="mv mw gp gr mx my"><a href="https://github.com/dart-lang/sdk" rel="noopener  ugc nofollow" target="_blank"><div class="mz ab fo"><div class="na ab nb cl cj nc"><h2 class="bd iu gy z fp nd fr fs ne fu fw is bi translated">dart-lang/sdk</h2><div class="nf l"><h3 class="bd b gy z fp nd fr fs ne fu fw dk translated">Dart是:针对UI优化的:使用专门针对用户界面创建需求的编程语言进行开发…</h3></div><div class="ng l"><p class="bd b dl z fp nd fr fs ne fu fw dk translated">github.com</p></div></div><div class="nh l"><div class="np l nj nk nl nh nm jz my"/></div></div></a></div></div></div>    
</body>
</html>