<html>
<head>
<title>Here’s what you should know about Java Exception Handling</title>
<link href="../Styles/Style.css" type="text/css" rel="stylesheet"/>
</head>
<body>
<h1 class="translated">下面是您应该了解的Java异常处理</h1>
<blockquote>原文：<a href="https://levelup.gitconnected.com/heres-what-you-should-know-about-java-exception-handling-5ed08669ad21?source=collection_archive---------4-----------------------#2022-02-19">https://levelup.gitconnected.com/heres-what-you-should-know-about-java-exception-handling-5ed08669ad21?source=collection_archive---------4-----------------------#2022-02-19</a></blockquote><div><div class="fc ie if ig ih ii"/><div class="ij ik il im in"><div class=""/><figure class="gl gn jo jp jq jr gh gi paragraph-image"><div role="button" tabindex="0" class="js jt di ju bf jv"><div class="gh gi jn"><img src="../Images/e6b415042336eda28c4052d942070a84.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/0*96K1cqCVir3RLzdy"/></div></div><figcaption class="jy jz gj gh gi ka kb bd b be z dk translated">照片由<a class="ae kc" href="https://unsplash.com?utm_source=medium&amp;utm_medium=referral" rel="noopener ugc nofollow" target="_blank"> Unsplash </a>上的<a class="ae kc" href="https://unsplash.com/@clemhlrdt?utm_source=medium&amp;utm_medium=referral" rel="noopener ugc nofollow" target="_blank"> Clément Hélardot </a>拍摄</figcaption></figure><p id="0ca4" class="pw-post-body-paragraph kd ke iq kf b kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la ij bi translated">想象一下，你正在YouTube上看视频，突然，你的互联网连接断开了。app表现如何？会崩溃吗？不，它只是给你显示信息，“没有互联网连接”。</p><p id="1fe2" class="pw-post-body-paragraph kd ke iq kf b kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la ij bi translated">不管你的代码有多棒，有些事情就是超出了你的控制范围！如果你的代码的一部分依赖于外部行为，比如互联网连接，那就不能保证你的代码会一直工作。</p><p id="a9b3" class="pw-post-body-paragraph kd ke iq kf b kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la ij bi translated">幸运的是，Java提供了一种机制来处理这些情况，称为<strong class="kf ir">异常处理。</strong>在这篇文章中，我将通过例子解释异常处理中的重要关键字，以便您可以在下一个Java应用程序中实现它们。</p><h2 id="8ff6" class="lb lc iq bd ld le lf dn lg lh li dp lj ko lk ll lm ks ln lo lp kw lq lr ls lt bi translated">异常处理的重要性</h2><p id="a8ba" class="pw-post-body-paragraph kd ke iq kf b kg lu ki kj kk lv km kn ko lw kq kr ks lx ku kv kw ly ky kz la ij bi translated">我们先来了解一下异常处理的重要性。当你的代码没有按预期运行时，程序<strong class="kf ir">抛出</strong>异常。</p><p id="d769" class="pw-post-body-paragraph kd ke iq kf b kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la ij bi translated">例如，您的代码可能包含一个从服务器获取一些数据的函数。如果服务器关闭，您的代码将无法继续正常执行，因此，您的应用程序将崩溃。</p><p id="d4a7" class="pw-post-body-paragraph kd ke iq kf b kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la ij bi translated">因此，您需要编写处理这些情况的代码。如果您的代码与文件、服务器或线程一起工作，则不能保证它正常工作。因此，异常处理成为强制性的。</p><pre class="lz ma mb mc gt md me mf mg aw mh bi"><span id="946a" class="lb lc iq me b gy mi mj l mk ml">// Fetch data from the server<br/>String data = fetchData()</span><span id="24e6" class="lb lc iq me b gy mm mj l mk ml">/* There is no guarantee the above code would work as expected<br/>If the server is down, the flow of the program is interrupted and its execution stops. */</span><span id="6238" class="lb lc iq me b gy mm mj l mk ml">/* The subsequent code depends on the data */</span><span id="d077" class="lb lc iq me b gy mm mj l mk ml">...rest of the code ...</span></pre><p id="cb54" class="pw-post-body-paragraph kd ke iq kf b kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la ij bi translated">异常处理确保即使出现问题(抛出异常)，程序也能继续执行。它还帮助您理解代码在各种情况下引发的异常。</p><h1 id="75b1" class="mn lc iq bd ld mo mp mq lg mr ms mt lj mu mv mw lm mx my mz lp na nb nc ls nd bi translated">尝试捕捉块</h1><p id="a13e" class="pw-post-body-paragraph kd ke iq kf b kg lu ki kj kk lv km kn ko lw kq kr ks lx ku kv kw ly ky kz la ij bi translated">当你写一个可能不起作用的函数(有风险的函数)时，你需要处理它抛出的异常。以下面的方式用try-catch块包围有风险的函数。</p><pre class="lz ma mb mc gt md me mf mg aw mh bi"><span id="e23d" class="lb lc iq me b gy mi mj l mk ml">try{<br/>    riskyFunction();  // Function that might throw an exception<br/>} catch(Exception e){<br/>  // Handle exception here<br/>}</span><span id="6981" class="lb lc iq me b gy mm mj l mk ml">...rest of the code...</span></pre><p id="4b4d" class="pw-post-body-paragraph kd ke iq kf b kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la ij bi translated">这里，如果try块内部出错(本例中为<em class="ne">risky function)</em>，catch块内部的代码将被执行。这类似于生活；“尝试一些有风险的事情，但如果不起作用，一定要抓住任何问题”。(注意:<em class="ne">如果定义了try块，就得定义catch或者finally块，否则编译器抛出错误)。</em></p><p id="ef3e" class="pw-post-body-paragraph kd ke iq kf b kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la ij bi translated">catch中的参数是包含代码抛出的异常的异常对象。在Java中，Exception是一个具有各种子类的类，这些子类指示特定类型的异常，例如ArithmeticException。参考<a class="ae kc" href="https://rollbar.com/blog/java-exceptions-hierarchy-explained" rel="noopener ugc nofollow" target="_blank">本</a>了解异常类层级，即其子类。</p><p id="30dd" class="pw-post-body-paragraph kd ke iq kf b kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la ij bi translated">让我们以从远程服务器获取数据的代码为例。<em class="ne">数据</em>被声明为列表类型变量，因为服务器被期望发送列表。</p><pre class="lz ma mb mc gt md me mf mg aw mh bi"><span id="fb0a" class="lb lc iq me b gy mi mj l mk ml">List data=null;<br/>try{<br/>      data=fetchData();<br/>} catch(IOException e){<br/>   // Handle exception here<br/>}</span></pre><p id="379f" class="pw-post-body-paragraph kd ke iq kf b kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la ij bi translated">try块中的代码从远程服务器获取数据。如果无法连接到服务器，该函数将抛出一个异常(<a class="ae kc" href="https://docs.oracle.com/javase/7/docs/api/java/io/IOException.html" rel="noopener ugc nofollow" target="_blank"> IOException </a>)。</p><p id="9db5" class="pw-post-body-paragraph kd ke iq kf b kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la ij bi translated">现在，让我们假设服务器响应，但不发送任何数据。<em class="ne">数据</em>变量仍然为空，如果您试图使用<em class="ne">数据</em>执行任何操作，代码将抛出另一个异常(<strong class="kf ir">NullPointerException(hyperlink this)</strong>)。</p><p id="f021" class="pw-post-body-paragraph kd ke iq kf b kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la ij bi translated">一个try块可以有多个catch块。</p><pre class="lz ma mb mc gt md me mf mg aw mh bi"><span id="516e" class="lb lc iq me b gy mi mj l mk ml">Object data=null;<br/>try{<br/>      data=fetchData();</span><span id="c869" class="lb lc iq me b gy mm mj l mk ml">      // Get the first element of the list <br/>      System.out.println(data.get(0));</span><span id="689d" class="lb lc iq me b gy mm mj l mk ml">} catch(IOException e){<br/>   // Handle IOException here<br/>} catch(NullPointerException e){<br/>   // Handle NullPointerException here<br/>} catch(Exception e){<br/>   // Handle any other exceptions here<br/>}</span></pre><p id="f866" class="pw-post-body-paragraph kd ke iq kf b kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la ij bi translated">这里，我处理了代码可能抛出的两个异常。虽然这里不是这样，但是如果您的代码可能抛出更多您不知道的异常，它们将在第三个catch块中处理。因为Exception是一个超类，所以它可以保存任何异常对象。</p><p id="a532" class="pw-post-body-paragraph kd ke iq kf b kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la ij bi translated">如果您想以同样的方式处理异常，您可以编写一个catch块。</p><pre class="lz ma mb mc gt md me mf mg aw mh bi"><span id="617b" class="lb lc iq me b gy mi mj l mk ml">Object data=null;<br/>try{<br/>      data=fetchData();</span><span id="52e4" class="lb lc iq me b gy mm mj l mk ml">// Get the first element of the list <br/>      System.out.println(data.get(0));</span><span id="d65f" class="lb lc iq me b gy mm mj l mk ml">} catch(Exception e){<br/>   // Handle your exceptions here<br/>}</span></pre><h1 id="ebdd" class="mn lc iq bd ld mo mp mq lg mr ms mt lj mu mv mw lm mx my mz lp na nb nc ls nd bi translated">最终块</h1><p id="48ce" class="pw-post-body-paragraph kd ke iq kf b kg lu ki kj kk lv km kn ko lw kq kr ks lx ku kv kw ly ky kz la ij bi translated">无论是否发生异常，该块都用于编写“清理”代码。什么是清理代码？如果你的危险函数打开了任何文件或服务器/数据库连接，你需要在最后关闭它们以避免任何<a class="ae kc" href="https://quora.com/What-is-resource-leak-in-Java" rel="noopener ugc nofollow" target="_blank">资源泄漏</a>。</p><p id="5570" class="pw-post-body-paragraph kd ke iq kf b kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la ij bi translated">不管有什么异常，<em class="ne"> finally </em>块总是会执行，所以在块内编写任何清理代码是有意义的。</p><p id="10d5" class="pw-post-body-paragraph kd ke iq kf b kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la ij bi translated">假设我们已经打开了一个到服务器的连接。</p><pre class="lz ma mb mc gt md me mf mg aw mh bi"><span id="403c" class="lb lc iq me b gy mi mj l mk ml">try{<br/>    openConnection();<br/> // Other risky operations</span><span id="bd9e" class="lb lc iq me b gy mm mj l mk ml">} catch(Exception e){<br/>   // Handle exception here<br/>} finally {<br/>  //  Cleanup code<br/>    closeConnection();<br/>}</span></pre><p id="4fde" class="pw-post-body-paragraph kd ke iq kf b kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la ij bi translated">我们有一个<em class="ne"> catch </em>块来处理任何异常，还有一个<em class="ne"> finally </em>块来关闭连接。这里，关闭连接是您的清理代码。</p><p id="e9f2" class="pw-post-body-paragraph kd ke iq kf b kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la ij bi translated">如果你有一个<em class="ne">最终</em>块，你可以跳过<em class="ne">捕捉</em>块。</p><pre class="lz ma mb mc gt md me mf mg aw mh bi"><span id="60d7" class="lb lc iq me b gy mi mj l mk ml">try{<br/>    openConnection(); <br/> ...Other risky operations...</span><span id="3916" class="lb lc iq me b gy mm mj l mk ml">} finally {<br/>  //  Cleanup code<br/>    closeConnection();<br/>}</span></pre><h1 id="4f9a" class="mn lc iq bd ld mo mp mq lg mr ms mt lj mu mv mw lm mx my mz lp na nb nc ls nd bi translated">投掷vs投掷</h1><p id="bcbf" class="pw-post-body-paragraph kd ke iq kf b kg lu ki kj kk lv km kn ko lw kq kr ks lx ku kv kw ly ky kz la ij bi translated">当你捕捉到一个异常时，必须有一个抛出它的函数。我们把它贴上了风险函数的标签。在它的实现中，您会发现显式代码，用于在出现问题时抛出异常。</p><p id="a7e6" class="pw-post-body-paragraph kd ke iq kf b kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la ij bi translated">以如下方式使用<em class="ne"> throw </em>关键字抛出异常:</p><pre class="lz ma mb mc gt md me mf mg aw mh bi"><span id="3c86" class="lb lc iq me b gy mi mj l mk ml">void riskyFunction() {<br/>    ...rest of the code...<br/>    <br/>    // Throw an exception if something went wrong<br/>    if (something wrong):<br/>       throw new Exception('This is an exception');<br/>    <br/>    ...rest of the code<br/>}</span><span id="5045" class="lb lc iq me b gy mm mj l mk ml">try{<br/>    riskyFunction();<br/>} catch(Exception e){<br/>    // Handle Excepion<br/>}</span></pre><p id="1b8f" class="pw-post-body-paragraph kd ke iq kf b kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la ij bi translated"><em class="ne"> throw </em>关键字后面是一个异常对象。构造函数的参数是引发异常时显示的消息。但是<em class="ne">扔</em>和<em class="ne">扔</em>有什么区别呢？</p><p id="bce0" class="pw-post-body-paragraph kd ke iq kf b kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la ij bi translated"><em class="ne">抛出</em>显式抛出异常。如果执行了<em class="ne"> throw </em>关键字，您必须处理异常(使用<em class="ne"> catch </em>或<em class="ne"> finally) </em>，否则您的代码将停止执行。</p><pre class="lz ma mb mc gt md me mf mg aw mh bi"><span id="95dc" class="lb lc iq me b gy mi mj l mk ml">try{<br/>    throw new ArithmeticException();<br/>} catch(ArithmeticException e){<br/>  // Handle exception here<br/>}</span></pre><p id="7030" class="pw-post-body-paragraph kd ke iq kf b kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la ij bi translated">上面的代码抛出一个算术异常，然后在<em class="ne"> catch </em>块中进行处理。</p><p id="b941" class="pw-post-body-paragraph kd ke iq kf b kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la ij bi translated">同时，<em class="ne">抛出</em>关键字来声明一个异常。它与函数声明一起使用。<em class="ne">抛出</em>告诉你函数可能抛出一个异常，你最好在调用函数的任何地方处理这个异常。</p><p id="c9ca" class="pw-post-body-paragraph kd ke iq kf b kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la ij bi translated">让我们看看它是如何做到的:</p><pre class="lz ma mb mc gt md me mf mg aw mh bi"><span id="f7ec" class="lb lc iq me b gy mi mj l mk ml">// Declare the exception along with the function definition<br/>void function() throws Exception {<br/>    ...function implementation...<br/>    if (something wrong)<br/>        throw new Exception('Message');<br/>    else<br/>        ...normal flow...<br/>}</span></pre><p id="9b3e" class="pw-post-body-paragraph kd ke iq kf b kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la ij bi translated">这里，我们声明了一个例外。如果出错，该函数会抛出一个异常(任何类型的)。调用此函数时，处理异常。</p><pre class="lz ma mb mc gt md me mf mg aw mh bi"><span id="f941" class="lb lc iq me b gy mi mj l mk ml">try{<br/>    function();<br/>} catch(Exception e){<br/>    // Handle exception here<br/>}</span></pre><p id="400d" class="pw-post-body-paragraph kd ke iq kf b kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la ij bi translated"><em class="ne"> throws </em>关键字不抛出异常或中断程序流程。它只通知你和编译器一个可能的异常。</p><h1 id="f82a" class="mn lc iq bd ld mo mp mq lg mr ms mt lj mu mv mw lm mx my mz lp na nb nc ls nd bi translated">结论</h1><p id="1958" class="pw-post-body-paragraph kd ke iq kf b kg lu ki kj kk lv km kn ko lw kq kr ks lx ku kv kw ly ky kz la ij bi translated">在现实世界的应用中，事情很少按照计划进行。您的代码在执行过程中可能会遇到意外问题。因此，异常处理成为Java应用程序的必要组成部分。</p><p id="cc3c" class="pw-post-body-paragraph kd ke iq kf b kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la ij bi translated">在这篇文章中，我用例子解释了异常处理中的重要关键词。这些关键词是相互依存的。如果没有抛出异常，就无法捕捉到它。此外，<em class="ne">投掷</em>和<em class="ne">投掷</em>的区别已经用实例说明。</p><p id="4bd3" class="pw-post-body-paragraph kd ke iq kf b kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv kw kx ky kz la ij bi translated">好吧！今天到此为止。如果您无法理解内容或对解释不满意，请在下面评论您的想法。新想法总是受欢迎的！如果你喜欢这篇文章，请鼓掌。订阅并关注我的每周内容。此外，请务必查看我的其他<a class="ae kc" href="https://medium.com/@kunal.nalawade25" rel="noopener">帖子</a>。到那时，再见！！</p></div></div>    
</body>
</html>