<html>
<head>
<title>JavaScript Try-Catch Error and Exception Handling Guide</title>
<link href="../Styles/Style.css" type="text/css" rel="stylesheet"/>
</head>
<body>
<h1 class="translated">JavaScript Try-Catch错误和异常处理指南</h1>
<blockquote>原文：<a href="https://levelup.gitconnected.com/javascript-try-catch-error-and-exception-handling-guide-352526468245?source=collection_archive---------8-----------------------#2022-10-17">https://levelup.gitconnected.com/javascript-try-catch-error-and-exception-handling-guide-352526468245?source=collection_archive---------8-----------------------#2022-10-17</a></blockquote><div><div class="fc ie if ig ih ii"/><div class="ij ik il im in"><div class=""/><figure class="gl gn jo jp jq jr gh gi paragraph-image"><div role="button" tabindex="0" class="js jt di ju bf jv"><div class="gh gi jn"><img src="../Images/7149e3a74361bda33c322bd321291afc.png" data-original-src="https://miro.medium.com/v2/resize:fit:1400/format:webp/1*i0-ZubqP-XVjOUpon7SMZA.png"/></div></div></figure><p id="f12d" class="pw-post-body-paragraph jy jz iq ka b kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv ij bi translated">在任何软件开发项目中，处理错误和异常对于应用程序的成功至关重要。无论您是新手还是专家，您的代码都可能因为各种原因而失败，比如一个简单的输入错误或外部服务的意外行为。</p><p id="6607" class="pw-post-body-paragraph jy jz iq ka b kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv ij bi translated">因为您的代码总是有可能失败，所以您需要通过使您的代码更加健壮来为这种情况做准备。您可以通过多种方式做到这一点，但是一个常见的解决方案是使用<code class="fe kw kx ky kz b">try-catch</code>语句。此语句允许您包装代码块来尝试和执行。如果在执行过程中出现任何错误，该语句将“捕捉”它们，您可以在应用程序崩溃之前快速修复它们。</p><p id="327d" class="pw-post-body-paragraph jy jz iq ka b kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv ij bi translated">本文将作为对<code class="fe kw kx ky kz b">try-catch</code>语句的实用介绍，并向您展示如何使用它们来处理JavaScript中的错误。</p><h1 id="3750" class="la lb iq bd lc ld le lf lg lh li lj lk ll lm ln lo lp lq lr ls lt lu lv lw lx bi translated">1.<strong class="ak">为什么需要试捕</strong></h1><p id="05a9" class="pw-post-body-paragraph jy jz iq ka b kb ly kd ke kf lz kh ki kj ma kl km kn mb kp kq kr mc kt ku kv ij bi translated">当你不遵循特定编程语言的规则时，就会出现语法错误。这些错误可以通过配置linter来检测，linter是一种用于分析代码和标记风格或编程错误的工具。例如，您可以使用ESLint来查找并修复代码问题中的bug。</p><p id="d933" class="pw-post-body-paragraph jy jz iq ka b kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv ij bi translated">下面是一个语法错误的例子:</p><pre class="md me mf mg gt mh kz mi mj aw mk bi"><span id="1d25" class="ml lb iq kz b gy mm mn l mo mp">console.log(;)</span></pre><p id="310c" class="pw-post-body-paragraph jy jz iq ka b kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv ij bi translated">在这种情况下，发生错误是因为代码的语法不正确。应该是这样的:</p><pre class="md me mf mg gt mh kz mi mj aw mk bi"><span id="8a91" class="ml lb iq kz b gy mm mn l mo mp">console.log('Maxwell');</span></pre><p id="e6a6" class="pw-post-body-paragraph jy jz iq ka b kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv ij bi translated">当应用程序运行有问题时，就会出现运行时错误。例如，您的代码可能试图调用一个不存在的方法。要捕捉这些错误并应用一些处理，可以使用<code class="fe kw kx ky kz b">try-catch</code>语句。</p><h1 id="987b" class="la lb iq bd lc ld le lf lg lh li lj lk ll lm ln lo lp lq lr ls lt lu lv lw lx bi translated">2.<strong class="ak">什么是异常</strong></h1><p id="d507" class="pw-post-body-paragraph jy jz iq ka b kb ly kd ke kf lz kh ki kj ma kl km kn mb kp kq kr mc kt ku kv ij bi translated">异常是一个对象，表示在程序执行过程中出现了问题。当访问无效的数组索引时，当试图访问空引用的某个成员时，当试图调用不存在的函数时，会出现这些问题。</p><p id="c3ec" class="pw-post-body-paragraph jy jz iq ka b kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv ij bi translated">例如，考虑一个应用程序依赖于第三方API的场景。您的代码可能会处理来自此API的响应，期望它们包含某些属性。如果这个API由于某种原因返回了一个意外的响应，它可能会触发一个运行时错误。在这种情况下，您可以将受影响的逻辑封装在一个<code class="fe kw kx ky kz b">try-catch</code>语句中，并向用户提供一条错误消息，甚至调用一些回退逻辑，而不是让错误导致应用程序崩溃。</p><h1 id="4f71" class="la lb iq bd lc ld le lf lg lh li lj lk ll lm ln lo lp lq lr ls lt lu lv lw lx bi translated">3.<strong class="ak">试捕的工作原理</strong></h1><p id="cbc8" class="pw-post-body-paragraph jy jz iq ka b kb ly kd ke kf lz kh ki kj ma kl km kn mb kp kq kr mc kt ku kv ij bi translated">简单地说，<code class="fe kw kx ky kz b">try-catch</code>语句由两个代码块组成——一个以<code class="fe kw kx ky kz b">try</code>关键字为前缀，另一个以<code class="fe kw kx ky kz b">catch</code>关键字为前缀——以及一个存储错误对象变量名的代码块。如果<code class="fe kw kx ky kz b">try</code>块中的代码抛出错误，该错误将被传递给<code class="fe kw kx ky kz b">catch</code>块进行处理。如果它不抛出错误，就永远不会调用<code class="fe kw kx ky kz b">catch</code>块。考虑下面的例子:</p><figure class="md me mf mg gt jr"><div class="bz fp l di"><div class="mq mr l"/></div></figure><p id="095f" class="pw-post-body-paragraph jy jz iq ka b kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv ij bi translated">在此示例中，当调用该函数时，运行时将看到没有这样的函数，并引发错误。多亏了围绕它的<code class="fe kw kx ky kz b">try-catch</code>语句，这个错误不是致命的，可以按照您喜欢的方式处理。在这种情况下，它被传递给<code class="fe kw kx ky kz b">console.log</code>，告诉您错误是什么。</p><p id="431a" class="pw-post-body-paragraph jy jz iq ka b kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv ij bi translated">还有另一个可选语句叫做<code class="fe kw kx ky kz b">finally</code>语句，当存在时，总是在<code class="fe kw kx ky kz b">try</code>和<code class="fe kw kx ky kz b">catch</code>之后执行，不管<code class="fe kw kx ky kz b">catch</code>是否执行。它通常用于包含释放在<code class="fe kw kx ky kz b">try</code>语句中分配的资源的命令，这些资源在发生错误时可能没有机会正常清理。考虑下面的例子:</p><figure class="md me mf mg gt jr"><div class="bz fp l di"><div class="mq mr l"/></div></figure><p id="2bc7" class="pw-post-body-paragraph jy jz iq ka b kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv ij bi translated">在这个虚构的例子中，假设在<code class="fe kw kx ky kz b">try-catch-finally</code>语句之前打开了一个文件。如果在<code class="fe kw kx ky kz b">try</code>程序块中出现错误，确保关闭文件以避免内存泄漏或死锁。在本例中，<code class="fe kw kx ky kz b">finally</code>语句确保无论<code class="fe kw kx ky kz b">try-catch</code>如何执行，文件都将在继续之前关闭。</p><p id="e625" class="pw-post-body-paragraph jy jz iq ka b kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv ij bi translated">当然，用try-catch语句包装可能容易出错的代码只是容错难题的一部分。另一部分是知道当抛出错误时该做什么。</p><p id="552b" class="pw-post-body-paragraph jy jz iq ka b kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv ij bi translated">有时向用户显示它们可能是有意义的(通常以更易读的格式)，有时您可能想简单地记录它们以供将来参考。无论哪种方式，熟悉错误对象本身都会有所帮助，这样您就知道必须处理什么数据。</p><h1 id="0b61" class="la lb iq bd lc ld le lf lg lh li lj lk ll lm ln lo lp lq lr ls lt lu lv lw lx bi translated">4.<strong class="ak">错误对象</strong></h1><p id="5f63" class="pw-post-body-paragraph jy jz iq ka b kb ly kd ke kf lz kh ki kj ma kl km kn mb kp kq kr mc kt ku kv ij bi translated">每当在<code class="fe kw kx ky kz b">try</code>语句中抛出异常时，JavaScript就会创建一个<code class="fe kw kx ky kz b">Error</code>对象，并将其作为参数发送给<code class="fe kw kx ky kz b">catch</code>语句。通常，该对象有两个主要的实例属性:</p><ul class=""><li id="d022" class="ms mt iq ka b kb kc kf kg kj mu kn mv kr mw kv mx my mz na bi translated"><code class="fe kw kx ky kz b">name</code>:描述错误类型的字符串</li><li id="f120" class="ms mt iq ka b kb nb kf nc kj nd kn ne kr nf kv mx my mz na bi translated"><code class="fe kw kx ky kz b">message</code>:更详细的错误描述</li></ul><figure class="md me mf mg gt jr"><div class="bz fp l di"><div class="mq mr l"/></div></figure><p id="7b64" class="pw-post-body-paragraph jy jz iq ka b kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv ij bi translated">如前所述，<code class="fe kw kx ky kz b">name</code>属性的值指的是发生的错误类型。以下是一些更常见的错误类型的非详尽列表:</p><ul class=""><li id="f55c" class="ms mt iq ka b kb kc kf kg kj mu kn mv kr mw kv mx my mz na bi translated"><code class="fe kw kx ky kz b">ReferenceError</code>:当检测到对不存在或无效的变量或函数的引用时，抛出<code class="fe kw kx ky kz b">ReferenceError</code>。</li><li id="c26e" class="ms mt iq ka b kb nb kf nc kj nd kn ne kr nf kv mx my mz na bi translated"><code class="fe kw kx ky kz b">TypeError</code>:当一个值被以与其类型不兼容的方式使用时，比如试图调用一个数字字符串函数(<code class="fe kw kx ky kz b">(1).split(',');</code>)，就会抛出一个<code class="fe kw kx ky kz b">TypeError</code>。</li><li id="90c3" class="ms mt iq ka b kb nb kf nc kj nd kn ne kr nf kv mx my mz na bi translated"><code class="fe kw kx ky kz b">SyntaxError</code> : <code class="fe kw kx ky kz b">SyntaxError</code>在解释代码时出现语法错误时抛出；比如解析JSON的时候用一个尾随逗号(<code class="fe kw kx ky kz b">JSON.parse('[1,2,3,4,]');</code>)。</li><li id="4011" class="ms mt iq ka b kb nb kf nc kj nd kn ne kr nf kv mx my mz na bi translated"><code class="fe kw kx ky kz b">SyntaxError</code> : <code class="fe kw kx ky kz b">URIError</code>在URI处理中出现错误时抛出；例如，在<code class="fe kw kx ky kz b">decodeURI()</code>或<code class="fe kw kx ky kz b">encodeURI()</code>中传递了无效参数。</li><li id="c5a9" class="ms mt iq ka b kb nb kf nc kj nd kn ne kr nf kv mx my mz na bi translated"><code class="fe kw kx ky kz b">RangeError</code> : <code class="fe kw kx ky kz b">RangeError</code>当值不在允许值的集合或范围内时抛出；例如，数字数组中的字符串值。</li></ul><p id="d120" class="pw-post-body-paragraph jy jz iq ka b kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv ij bi translated">所有本地JavaScript错误都是通用<code class="fe kw kx ky kz b">Error</code>对象的扩展。遵循这一原则，您也可以创建自己的错误类型。</p><h1 id="bc0a" class="la lb iq bd lc ld le lf lg lh li lj lk ll lm ln lo lp lq lr ls lt lu lv lw lx bi translated">5.自定义错误</h1><p id="6624" class="pw-post-body-paragraph jy jz iq ka b kb ly kd ke kf lz kh ki kj ma kl km kn mb kp kq kr mc kt ku kv ij bi translated">JavaScript中另一个与错误和错误处理密切相关的关键字是<code class="fe kw kx ky kz b">throw</code>。使用该关键字时，可以“抛出”用户定义的异常。当您这样做时，当前函数的执行将停止，任何与<code class="fe kw kx ky kz b">throw</code>关键字一起使用的值将被传递给调用堆栈中的第一个<code class="fe kw kx ky kz b">catch</code>语句。如果没有一个<code class="fe kw kx ky kz b">catch</code>语句来处理它，行为将类似于一个典型的未处理的错误，程序将终止。</p><p id="72ea" class="pw-post-body-paragraph jy jz iq ka b kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv ij bi translated">抛出<strong class="ka ir">自定义错误</strong>在更复杂的应用程序中很有用，因为它给了你另一种控制代码流的方法。考虑一个场景，您需要验证一些用户输入。如果根据业务规则，输入被认为是无效的，您不想继续处理请求。这是<code class="fe kw kx ky kz b">throw</code>语句的一个完美用例。考虑下面的例子:</p><figure class="md me mf mg gt jr"><div class="bz fp l di"><div class="mq mr l"/></div></figure><p id="e52c" class="pw-post-body-paragraph jy jz iq ka b kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv ij bi translated">这里定义了一个自定义错误类，它可以扩展通用错误类。这种技术可以用来抛出与业务逻辑相关的错误，而不仅仅是JavaScript引擎使用的默认错误。</p><h1 id="cf3b" class="la lb iq bd lc ld le lf lg lh li lj lk ll lm ln lo lp lq lr ls lt lu lv lw lx bi translated">6.<strong class="ak">何时使用Try-Catch </strong></h1><p id="e532" class="pw-post-body-paragraph jy jz iq ka b kb ly kd ke kf lz kh ki kj ma kl km kn mb kp kq kr mc kt ku kv ij bi translated">因为错误会沿着调用堆栈向上爬，直到找到一个<code class="fe kw kx ky kz b">try-catch</code>语句或应用程序终止，所以很容易将整个应用程序包装在一个大的<code class="fe kw kx ky kz b">try-catch</code>语句或许多更小的<code class="fe kw kx ky kz b">try-catch</code>语句中，这样您就可以享受应用程序在技术上不会再次崩溃的事实。然而，这不是一个好主意。</p><p id="e4c3" class="pw-post-body-paragraph jy jz iq ka b kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv ij bi translated">说到编程，bug是一个事实，它们在应用程序的生命周期中扮演着重要的角色。他们会告诉你哪里出了问题。因此，如果您想为您的用户提供良好的体验，您必须尊重并小心地使用try-catch语句。</p><p id="95f8" class="pw-post-body-paragraph jy jz iq ka b kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv ij bi translated"><code class="fe kw kx ky kz b">try-catch</code>通常应在合理预期会发生错误的情况下使用语句。然而，一旦你发现一个错误，你通常不想直接删除它。如前所述，当抛出错误时，意味着发生了错误。您应该利用这个机会适当地处理错误，要么在UI中向用户显示更好的错误消息，要么将错误发送到应用程序监视工具(如果有)进行汇总和以后的分析。</p><p id="7690" class="pw-post-body-paragraph jy jz iq ka b kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv ij bi translated">一般来说，当在<code class="fe kw kx ky kz b">try-catch</code>语句中包装代码时，您应该只包装概念上与预期错误相关的代码。如果函数的大小相当小，这可能意味着要包装整个函数体。或者，您可能有一个更大的函数，其中主体中的所有代码都被包装，但是分布在多个<code class="fe kw kx ky kz b">try-catch</code>语句中。这实际上可以作为一种指示，表明所讨论的特性太复杂和/或处理太多的责任。这样的代码可以被分解成更小、更集中的函数。</p><p id="23f1" class="pw-post-body-paragraph jy jz iq ka b kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv ij bi translated">对于不太可能发生错误的代码区域，通常最好放弃过多的try-catch语句，允许错误发生。这听起来可能违反直觉，但是允许您的代码快速失败实际上是将您自己置于一个更好的位置。压缩错误可能会产生稳定的外观，但仍然存在潜在的问题。</p><p id="b4b1" class="pw-post-body-paragraph jy jz iq ka b kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv ij bi translated">允许错误发生而不进行显式处理意味着，当与应用程序监控工具(如<em class="ng"> BugSnag </em>或<em class="ng"> Sentry </em>)交互时，您可以全局拦截并记录错误，以供以后分析。这些工具允许您看到应用程序中的错误实际在哪里，以便您可以修复它们，而不是盲目地忽略它们。</p><h1 id="75ed" class="la lb iq bd lc ld le lf lg lh li lj lk ll lm ln lo lp lq lr ls lt lu lv lw lx bi translated">7.异步功能</h1><p id="f5f9" class="pw-post-body-paragraph jy jz iq ka b kb ly kd ke kf lz kh ki kj ma kl km kn mb kp kq kr mc kt ku kv ij bi translated">要理解JavaScript中的异步函数是什么，你必须理解<a class="ae nh" href="https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise" rel="noopener ugc nofollow" target="_blank"> Promise </a></p><p id="6d45" class="pw-post-body-paragraph jy jz iq ka b kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv ij bi translated">一个<code class="fe kw kx ky kz b">promise</code>本质上是一个表示异步操作最终完成的对象。它们定义了将来要执行的动作，这些动作最终会是<code class="fe kw kx ky kz b">resolve</code>(成功)或<code class="fe kw kx ky kz b">reject</code>(错误)。</p><p id="6f8c" class="pw-post-body-paragraph jy jz iq ka b kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv ij bi translated">例如，下面的代码显示了一个简单的<code class="fe kw kx ky kz b">Promise</code>，它可以快速解析一个值。然后将该值传递给<code class="fe kw kx ky kz b">then</code>回调函数:</p><figure class="md me mf mg gt jr"><div class="bz fp l di"><div class="mq mr l"/></div></figure><p id="bde2" class="pw-post-body-paragraph jy jz iq ka b kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv ij bi translated">下一个例子展示了<code class="fe kw kx ky kz b">Promise</code>中抛出的错误如何被<code class="fe kw kx ky kz b">Promise</code> <code class="fe kw kx ky kz b">catch</code>回调处理:</p><figure class="md me mf mg gt jr"><div class="bz fp l di"><div class="mq mr l"/></div></figure><p id="70ed" class="pw-post-body-paragraph jy jz iq ka b kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv ij bi translated">您可以使用<code class="fe kw kx ky kz b">reject</code>函数，而不是手动在<code class="fe kw kx ky kz b">promise</code>中抛出错误。该函数作为<code class="fe kw kx ky kz b">Promise</code>回调函数的第二个参数提供:</p><figure class="md me mf mg gt jr"><div class="bz fp l di"><div class="mq mr l"/></div></figure><p id="f8b5" class="pw-post-body-paragraph jy jz iq ka b kb kc kd ke kf kg kh ki kj kk kl km kn ko kp kq kr ks kt ku kv ij bi translated">您可能会注意到上一个示例中的一些奇怪之处。<strong class="ka ir">抛出错误</strong>和<code class="fe kw kx ky kz b">reject</code>是有区别的。抛出错误将停止代码的执行，并将错误传递给最近的<code class="fe kw kx ky kz b">catch</code>语句或终止程序。<code class="fe kw kx ky kz b">reject</code>一个<code class="fe kw kx ky kz b">Promise</code>将调用<code class="fe kw kx ky kz b">catch</code>回调函数，但如果有更多代码要运行，它不会停止<code class="fe kw kx ky kz b">Promise</code>的执行，除非对<code class="fe kw kx ky kz b">reject</code>函数的调用以return关键字为前缀。这就是为什么<code class="fe kw kx ky kz b">console.log(a + b);</code>语句即使在<code class="fe kw kx ky kz b">reject</code>之后依然被炒。为了避免这种行为，只需使用<code class="fe kw kx ky kz b">return reject(…)</code>提前结束执行。</p><h1 id="6be5" class="la lb iq bd lc ld le lf lg lh li lj lk ll lm ln lo lp lq lr ls lt lu lv lw lx bi translated">8.总结</h1><p id="d3f4" class="pw-post-body-paragraph jy jz iq ka b kb ly kd ke kf lz kh ki kj ma kl km kn mb kp kq kr mc kt ku kv ij bi translated"><code class="fe kw kx ky kz b">try-catch</code>语句是一个有用的工具，在程序员的职业生涯中肯定会用到。但是，随便用什么方法都不一定是最好的解决方案。请记住，您需要使用正确的工具和概念来解决特定的问题。例如，当您不希望出现任何异常时，通常不使用<code class="fe kw kx ky kz b">try-catch</code>语句。如果在这些情况下确实发生了错误，您可以在它们发生时识别并修复它们。</p></div></div>    
</body>
</html>